<?php

declare(strict_types=1);

return [
    'categories' => [
        ['slug' => 'baslarken', 'name' => 'Güne Başlarken', 'heading' => 'Güne Başlarken', 'sort_order' => 1],
        ['slug' => 'diyet', 'name' => 'Diyet', 'heading' => 'Diyet Menü', 'sort_order' => 2],
        ['slug' => 'tostlar', 'name' => 'Tostlar', 'heading' => 'Tostlar', 'sort_order' => 3],
        ['slug' => 'gozleme', 'name' => 'Gözleme', 'heading' => 'Gözleme ve Atıştırmalıklar', 'sort_order' => 4],
        ['slug' => 'salatalar', 'name' => 'Salatalar', 'heading' => 'Salatalar', 'sort_order' => 5],
        ['slug' => 'makarnalar', 'name' => 'Makarnalar', 'heading' => 'Makarnalar', 'sort_order' => 6],
        ['slug' => 'burger', 'name' => 'Burger', 'heading' => 'Hamburgerler', 'sort_order' => 7],
        ['slug' => 'ogrenci', 'name' => 'Öğrenci Menü', 'heading' => 'Öğrenci Menü', 'sort_order' => 8],
        ['slug' => 'izgara', 'name' => 'Izgara', 'heading' => 'Izgaralar', 'sort_order' => 9],
        ['slug' => 'bitkicayi', 'name' => 'Bitki Çayları', 'heading' => 'Bitki Çayları', 'sort_order' => 10],
        ['slug' => 'sicak', 'name' => 'Sıcak İçecekler', 'heading' => 'Sıcak İçecekler', 'sort_order' => 11],
        ['slug' => 'sogukkahve', 'name' => 'Soğuk Kahve', 'heading' => 'Soğuk Kahve Çeşitleri', 'sort_order' => 12],
        ['slug' => 'soguk', 'name' => 'Soğuk İçecekler', 'heading' => 'Soğuk İçecekler', 'sort_order' => 13],
        ['slug' => 'tatlilar', 'name' => 'Tatlılar', 'heading' => 'Tatlılar', 'sort_order' => 14],
        ['slug' => 'kuruyemis', 'name' => 'Kuru Yemiş', 'heading' => 'Kuru Yemiş Tabağı', 'sort_order' => 15],
    ],
    'products' => [
        ['category_slug' => 'baslarken', 'name' => 'Günün Çorbası', 'description' => 'Günün Çorbası İçin Garsondan Bilgi Alınız.', 'note' => '', 'price' => 80.00, 'is_featured' => false, 'sort_order' => 1],
        ['category_slug' => 'baslarken', 'name' => 'Kahvaltı Tabağı', 'description' => 'Tereyağı, Bal, Sigara Böreği, Patates Kızartması, Peynir Çeşitleri, Salam, Zeytin, Reçel, Domates, Salatalık, Sahanda Yumurta', 'note' => '', 'price' => 400.00, 'is_featured' => false, 'sort_order' => 2],
        ['category_slug' => 'baslarken', 'name' => 'Serpme Kahvaltı', 'description' => 'Tereyağı, Bal, Sigara Böreği, Patates Kızartması, Peynir Çeşitleri, Salam, Zeytin, Reçel, Domates, Salatalık, Sahanda Yumurta, Kremalı Patates Tava', 'note' => 'İki kişilik', 'price' => 800.00, 'is_featured' => false, 'sort_order' => 3],
        ['category_slug' => 'baslarken', 'name' => 'Grup Kahvaltı', 'description' => 'Kavurmalı Yumurta, Menemen, Peynir, Zeytin, Bal, Tereyağ, Çikolata, Sahanda Yumurta, Sigara Böreği, Kremalı Patates Tava, Paneli Börek Çeşitleri ve Poğaça, Domates, Salatalık, Özel Hazırlanmış Çilekli Tart', 'note' => '10 kişiliktir. Randevu ile gelinmesi rica olunur.', 'price' => 3000.00, 'is_featured' => false, 'sort_order' => 4],
        ['category_slug' => 'baslarken', 'name' => 'Söğüş Tabağı', 'description' => 'Tereyağı, Bal, Beyaz Peynir, Kaşar Peynir, Domates, Salatalık', 'note' => '', 'price' => 350.00, 'is_featured' => false, 'sort_order' => 5],
        ['category_slug' => 'baslarken', 'name' => 'Sucuklu Yumurta', 'description' => 'Yumurta ve Sucuğun Eşsiz Buluşması', 'note' => '', 'price' => 270.00, 'is_featured' => false, 'sort_order' => 6],
        ['category_slug' => 'baslarken', 'name' => 'Sahanda Yumurta', 'description' => 'Tereyağlı, Eşsiz Yumurta Keyfi', 'note' => '', 'price' => 220.00, 'is_featured' => false, 'sort_order' => 7],
        ['category_slug' => 'baslarken', 'name' => 'Omlet', 'description' => 'Peynir, Kaşar', 'note' => '', 'price' => 250.00, 'is_featured' => false, 'sort_order' => 8],
        ['category_slug' => 'baslarken', 'name' => 'Menemen', 'description' => '', 'note' => '', 'price' => 280.00, 'is_featured' => false, 'sort_order' => 9],
        ['category_slug' => 'baslarken', 'name' => 'Muhlama', 'description' => 'Bol terayağlı, özel kars kaşar peynirli', 'note' => '', 'price' => 350.00, 'is_featured' => false, 'sort_order' => 10],
        ['category_slug' => 'diyet', 'name' => 'Yulaflı Tost Diyet', 'description' => 'Kaşar Peynir, Beyaz Peynir, Zeytin, Domates, Salatalık', 'note' => '', 'price' => 450.00, 'is_featured' => false, 'sort_order' => 11],
        ['category_slug' => 'diyet', 'name' => 'Yulaflı Pizza', 'description' => 'Etli ve tavuklu kaşarlı seçeneği ile biber, zeytin, mısır', 'note' => '', 'price' => 475.00, 'is_featured' => false, 'sort_order' => 12],
        ['category_slug' => 'tostlar', 'name' => 'Yengen Tost Tabağı', 'description' => 'Sucuk, Salam, Turşu, Domates, Patates, Ketçap, Mayonez', 'note' => '', 'price' => 380.00, 'is_featured' => false, 'sort_order' => 13],
        ['category_slug' => 'tostlar', 'name' => 'Gurme Tost', 'description' => 'Kaşar Peyniri, Salam, Sucuk, Cedar Peyniri', 'note' => '', 'price' => 370.00, 'is_featured' => false, 'sort_order' => 14],
        ['category_slug' => 'tostlar', 'name' => 'Kavurmalı Tost', 'description' => 'Et Kavurması ve Kaşar Peyniri', 'note' => '', 'price' => 370.00, 'is_featured' => false, 'sort_order' => 15],
        ['category_slug' => 'tostlar', 'name' => 'Bazlama Tost Tabağı — Kaşarlı', 'description' => '', 'note' => '', 'price' => 300.00, 'is_featured' => false, 'sort_order' => 16],
        ['category_slug' => 'tostlar', 'name' => 'Bazlama Tost Tabağı — Karışık', 'description' => '', 'note' => '', 'price' => 320.00, 'is_featured' => false, 'sort_order' => 17],
        ['category_slug' => 'tostlar', 'name' => 'Ayvalık Tost Tabağı — Kaşarlı', 'description' => '', 'note' => '', 'price' => 250.00, 'is_featured' => false, 'sort_order' => 18],
        ['category_slug' => 'tostlar', 'name' => 'Ayvalık Tost Tabağı — Karışık', 'description' => '', 'note' => '', 'price' => 270.00, 'is_featured' => false, 'sort_order' => 19],
        ['category_slug' => 'gozleme', 'name' => 'Beyaz Peynirli Kaşarlı Gözleme', 'description' => '', 'note' => '', 'price' => 260.00, 'is_featured' => false, 'sort_order' => 20],
        ['category_slug' => 'gozleme', 'name' => 'Patatesli Kaşarlı Gözleme', 'description' => '', 'note' => '', 'price' => 260.00, 'is_featured' => false, 'sort_order' => 21],
        ['category_slug' => 'gozleme', 'name' => 'Kıymalı Gözleme', 'description' => '', 'note' => '', 'price' => 290.00, 'is_featured' => false, 'sort_order' => 22],
        ['category_slug' => 'gozleme', 'name' => 'Karışık Gözleme', 'description' => 'Patates, Kıyma, Mantar Kaşar Peyniri', 'note' => '', 'price' => 300.00, 'is_featured' => false, 'sort_order' => 23],
        ['category_slug' => 'gozleme', 'name' => 'Sebzeli Börek', 'description' => 'Kaşar Peyniri, Kabak, Havuç', 'note' => '', 'price' => 350.00, 'is_featured' => false, 'sort_order' => 24],
        ['category_slug' => 'gozleme', 'name' => 'Sigara Böreği', 'description' => '8 adet Sigara Böreği, Domates, Salatalık ile servis edilir.', 'note' => '', 'price' => 280.00, 'is_featured' => false, 'sort_order' => 25],
        ['category_slug' => 'gozleme', 'name' => 'Mozerella Stick', 'description' => '', 'note' => '', 'price' => 350.00, 'is_featured' => false, 'sort_order' => 26],
        ['category_slug' => 'gozleme', 'name' => 'Combo Tabağı', 'description' => 'Soğan Halkası, Sosis, Nuget, Patates Cipsi', 'note' => '', 'price' => 400.00, 'is_featured' => false, 'sort_order' => 27],
        ['category_slug' => 'gozleme', 'name' => 'Lahmacun', 'description' => '', 'note' => '', 'price' => 90.00, 'is_featured' => false, 'sort_order' => 28],
        ['category_slug' => 'salatalar', 'name' => 'Sezar Salata', 'description' => '', 'note' => '', 'price' => 380.00, 'is_featured' => false, 'sort_order' => 29],
        ['category_slug' => 'salatalar', 'name' => 'Ton Balıklı Salata', 'description' => '', 'note' => '', 'price' => 400.00, 'is_featured' => false, 'sort_order' => 30],
        ['category_slug' => 'makarnalar', 'name' => 'Bolonez Soslu Makarna', 'description' => 'Kıyma ve Özel Sos', 'note' => '', 'price' => 400.00, 'is_featured' => false, 'sort_order' => 31],
        ['category_slug' => 'makarnalar', 'name' => 'Tortellini Makarna', 'description' => 'Tavuklu, Kremalı, Mantarlı', 'note' => '', 'price' => 400.00, 'is_featured' => false, 'sort_order' => 32],
        ['category_slug' => 'makarnalar', 'name' => 'Spagetti Makarna Domatesli', 'description' => '', 'note' => '', 'price' => 320.00, 'is_featured' => false, 'sort_order' => 33],
        ['category_slug' => 'makarnalar', 'name' => 'Kremalı, Mantarlı Makarna', 'description' => 'Tavuklu, Kremalı, Mantarlı', 'note' => '', 'price' => 380.00, 'is_featured' => false, 'sort_order' => 34],
        ['category_slug' => 'makarnalar', 'name' => 'All Arabbiatta Makarna (Acılı)', 'description' => '', 'note' => '', 'price' => 370.00, 'is_featured' => false, 'sort_order' => 35],
        ['category_slug' => 'makarnalar', 'name' => 'Ton Balıklı Makarna', 'description' => '', 'note' => '', 'price' => 400.00, 'is_featured' => false, 'sort_order' => 36],
        ['category_slug' => 'makarnalar', 'name' => 'Haluj (Çerkez Mantısı)', 'description' => 'Kıymalı', 'note' => '', 'price' => 450.00, 'is_featured' => true, 'sort_order' => 37],
        ['category_slug' => 'makarnalar', 'name' => 'Ev Yapımı Mantı', 'description' => 'Kendi Yapımımız', 'note' => '', 'price' => 450.00, 'is_featured' => false, 'sort_order' => 38],
        ['category_slug' => 'burger', 'name' => 'Hamburger Tabağı', 'description' => '', 'note' => '', 'price' => 390.00, 'is_featured' => false, 'sort_order' => 39],
        ['category_slug' => 'burger', 'name' => 'Et Hamburger Tabağı', 'description' => 'Özel Harmanlanmış Hamburger Köftesi', 'note' => '', 'price' => 450.00, 'is_featured' => false, 'sort_order' => 40],
        ['category_slug' => 'burger', 'name' => 'Chicken Burger', 'description' => '', 'note' => '', 'price' => 390.00, 'is_featured' => false, 'sort_order' => 41],
        ['category_slug' => 'burger', 'name' => 'Cheeseburger', 'description' => '', 'note' => '', 'price' => 420.00, 'is_featured' => false, 'sort_order' => 42],
        ['category_slug' => 'burger', 'name' => 'Elma Dilim Patates', 'description' => '', 'note' => '', 'price' => 270.00, 'is_featured' => false, 'sort_order' => 43],
        ['category_slug' => 'burger', 'name' => 'Chips', 'description' => '', 'note' => '', 'price' => 190.00, 'is_featured' => false, 'sort_order' => 44],
        ['category_slug' => 'burger', 'name' => 'Patso', 'description' => '', 'note' => '', 'price' => 160.00, 'is_featured' => false, 'sort_order' => 45],
        ['category_slug' => 'ogrenci', 'name' => 'Kumru Sandviç', 'description' => 'Sandviçlerin Yanında Küçük Ayran İkramımızdır.', 'note' => '', 'price' => 350.00, 'is_featured' => false, 'sort_order' => 46],
        ['category_slug' => 'ogrenci', 'name' => 'Köfte Sandviç', 'description' => 'Sandviçlerin Yanında Küçük Ayran İkramımızdır.', 'note' => '', 'price' => 350.00, 'is_featured' => false, 'sort_order' => 47],
        ['category_slug' => 'ogrenci', 'name' => 'Nuget Sandviç', 'description' => 'Sandviçlerin Yanında Küçük Ayran İkramımızdır.', 'note' => '', 'price' => 300.00, 'is_featured' => false, 'sort_order' => 48],
        ['category_slug' => 'ogrenci', 'name' => 'Crispi Sandviç', 'description' => 'Sandviçlerin Yanında Küçük Ayran İkramımızdır.', 'note' => '', 'price' => 300.00, 'is_featured' => false, 'sort_order' => 49],
        ['category_slug' => 'ogrenci', 'name' => 'Sosisli Sandviç', 'description' => 'Sandviçlerin Yanında Küçük Ayran İkramımızdır.', 'note' => '', 'price' => 300.00, 'is_featured' => false, 'sort_order' => 50],
        ['category_slug' => 'ogrenci', 'name' => 'Tavuk Dürüm', 'description' => 'Dürümlerin Yanında Küçük Ayran İkramımızdır.', 'note' => '', 'price' => 300.00, 'is_featured' => false, 'sort_order' => 51],
        ['category_slug' => 'ogrenci', 'name' => 'Köfte Dürüm', 'description' => 'Dürümlerin Yanında Küçük Ayran İkramımızdır.', 'note' => '', 'price' => 350.00, 'is_featured' => false, 'sort_order' => 52],
        ['category_slug' => 'ogrenci', 'name' => 'Kavurmalı Dürüm', 'description' => 'Dürümlerin Yanında Küçük Ayran İkramımızdır.', 'note' => '', 'price' => 300.00, 'is_featured' => false, 'sort_order' => 53],
        ['category_slug' => 'izgara', 'name' => 'Köfte Izgara', 'description' => 'Özel baharatlarla lezzetlendirilmiş köfte, cips, közlenmiş biber, domates ve pilav ile servis edilir.', 'note' => '', 'price' => 450.00, 'is_featured' => false, 'sort_order' => 54],
        ['category_slug' => 'izgara', 'name' => 'Tavuk Izgara', 'description' => 'Özel sosta bekletilmiş tavuk göğüsü ve tavuk pirzola cips, közlenmiş biber, domates ve pilav ile servis edilir.', 'note' => '', 'price' => 500.00, 'is_featured' => false, 'sort_order' => 55],
        ['category_slug' => 'izgara', 'name' => 'Karışık Izgara', 'description' => 'Köfte, tavuk göğüsü, pirzola ve kontürofile et domates ve pilav ile servis edilir.', 'note' => '', 'price' => 800.00, 'is_featured' => false, 'sort_order' => 56],
        ['category_slug' => 'izgara', 'name' => 'Et Izgara', 'description' => 'Özel sosta bekletilmiş et, cips, közlenmiş biber, domates ve pilav ile servis edilir.', 'note' => '', 'price' => 600.00, 'is_featured' => false, 'sort_order' => 57],
        ['category_slug' => 'izgara', 'name' => 'Ekmek Arası Köfte', 'description' => 'Özel baharatlarla lezzetlendirilmiş köfte, soğan, cips', 'note' => '', 'price' => 375.00, 'is_featured' => false, 'sort_order' => 58],
        ['category_slug' => 'izgara', 'name' => 'Köri Soslu Tavuk', 'description' => 'Krema ve özel sosla pişirilir yanında cips ile servis edilir.', 'note' => '', 'price' => 400.00, 'is_featured' => false, 'sort_order' => 59],
        ['category_slug' => 'izgara', 'name' => 'Et Saç Kavurma', 'description' => 'Özel sosta bekletilmiş et, biber, soğan, domates eşliğinde pişirilir lavaş ile servis edilir.', 'note' => '', 'price' => 600.00, 'is_featured' => false, 'sort_order' => 60],
        ['category_slug' => 'izgara', 'name' => 'Tavuk Saç Kavurma', 'description' => 'Özel sosta bekletilmiş tavuk, biber, soğan, domates eşliğinde pişirilir lavaş ile servis edilir.', 'note' => '', 'price' => 450.00, 'is_featured' => false, 'sort_order' => 61],
        ['category_slug' => 'izgara', 'name' => 'Tavuk Dürüm/Cips', 'description' => '', 'note' => '', 'price' => 350.00, 'is_featured' => false, 'sort_order' => 62],
        ['category_slug' => 'izgara', 'name' => 'Viyana Şnitzel', 'description' => 'Paneli tavuk, kaşar, cips', 'note' => '', 'price' => 350.00, 'is_featured' => false, 'sort_order' => 63],
        ['category_slug' => 'izgara', 'name' => 'Etli Wrap', 'description' => 'Et, festo sos, özel baharatlarımız ile', 'note' => '', 'price' => 400.00, 'is_featured' => false, 'sort_order' => 64],
        ['category_slug' => 'izgara', 'name' => 'Tavuklu Wrap', 'description' => 'Tavuk, festo sos, özel baharatlarımız ile', 'note' => '', 'price' => 350.00, 'is_featured' => false, 'sort_order' => 65],
        ['category_slug' => 'izgara', 'name' => 'Osmanlı Et Tava', 'description' => '', 'note' => '', 'price' => 700.00, 'is_featured' => false, 'sort_order' => 66],
        ['category_slug' => 'bitkicayi', 'name' => 'Ada Çayı', 'description' => '', 'note' => '', 'price' => 120.00, 'is_featured' => false, 'sort_order' => 67],
        ['category_slug' => 'bitkicayi', 'name' => 'Papatya Çayı', 'description' => '', 'note' => '', 'price' => 120.00, 'is_featured' => false, 'sort_order' => 68],
        ['category_slug' => 'bitkicayi', 'name' => 'Kış Çayı', 'description' => '', 'note' => '', 'price' => 120.00, 'is_featured' => false, 'sort_order' => 69],
        ['category_slug' => 'bitkicayi', 'name' => 'Ihlamur Çayı', 'description' => '', 'note' => '', 'price' => 120.00, 'is_featured' => false, 'sort_order' => 70],
        ['category_slug' => 'sicak', 'name' => 'Çay', 'description' => '', 'note' => '', 'price' => 30.00, 'is_featured' => false, 'sort_order' => 71],
        ['category_slug' => 'sicak', 'name' => 'Fincan Çay', 'description' => '', 'note' => '', 'price' => 60.00, 'is_featured' => false, 'sort_order' => 72],
        ['category_slug' => 'sicak', 'name' => 'Sahlep', 'description' => '', 'note' => '', 'price' => 170.00, 'is_featured' => false, 'sort_order' => 73],
        ['category_slug' => 'sicak', 'name' => 'Oralet', 'description' => 'Kivi, Kakao, Portakal, Karadut, Elma, Çilek, Muz, Nane, Limon', 'note' => '', 'price' => 45.00, 'is_featured' => false, 'sort_order' => 74],
        ['category_slug' => 'sicak', 'name' => 'Sıcak Çikolata', 'description' => '', 'note' => '', 'price' => 170.00, 'is_featured' => false, 'sort_order' => 75],
        ['category_slug' => 'sicak', 'name' => 'Beyaz Sıcak Çikolata', 'description' => '', 'note' => '', 'price' => 170.00, 'is_featured' => false, 'sort_order' => 76],
        ['category_slug' => 'sicak', 'name' => 'Türk Kahvesi', 'description' => '', 'note' => '', 'price' => 100.00, 'is_featured' => false, 'sort_order' => 77],
        ['category_slug' => 'sicak', 'name' => 'Double Türk Kahvesi', 'description' => '', 'note' => '', 'price' => 190.00, 'is_featured' => false, 'sort_order' => 78],
        ['category_slug' => 'sicak', 'name' => 'Damla Sakızlı Türk Kahvesi', 'description' => '', 'note' => '', 'price' => 100.00, 'is_featured' => false, 'sort_order' => 79],
        ['category_slug' => 'sicak', 'name' => 'Dibek Kahvesi', 'description' => '', 'note' => '', 'price' => 100.00, 'is_featured' => false, 'sort_order' => 80],
        ['category_slug' => 'sicak', 'name' => 'Karamel Macchiato', 'description' => '', 'note' => '', 'price' => 170.00, 'is_featured' => false, 'sort_order' => 81],
        ['category_slug' => 'sicak', 'name' => 'Latte Macchiato', 'description' => '', 'note' => '', 'price' => 170.00, 'is_featured' => false, 'sort_order' => 82],
        ['category_slug' => 'sicak', 'name' => 'Americano', 'description' => '', 'note' => '', 'price' => 170.00, 'is_featured' => false, 'sort_order' => 83],
        ['category_slug' => 'sicak', 'name' => 'Espresso', 'description' => '', 'note' => '', 'price' => 170.00, 'is_featured' => false, 'sort_order' => 84],
        ['category_slug' => 'sicak', 'name' => 'Latte', 'description' => '', 'note' => '', 'price' => 170.00, 'is_featured' => false, 'sort_order' => 85],
        ['category_slug' => 'sogukkahve', 'name' => 'Ice Latte', 'description' => '', 'note' => '', 'price' => 200.00, 'is_featured' => false, 'sort_order' => 86],
        ['category_slug' => 'sogukkahve', 'name' => 'Ice Americano', 'description' => '', 'note' => '', 'price' => 200.00, 'is_featured' => false, 'sort_order' => 87],
        ['category_slug' => 'sogukkahve', 'name' => 'Ice Karamel Latte', 'description' => '', 'note' => '', 'price' => 200.00, 'is_featured' => false, 'sort_order' => 88],
        ['category_slug' => 'sogukkahve', 'name' => 'Ice Mocha', 'description' => '', 'note' => '', 'price' => 200.00, 'is_featured' => false, 'sort_order' => 89],
        ['category_slug' => 'sogukkahve', 'name' => 'Ice Karamel Macchiato', 'description' => '', 'note' => '', 'price' => 200.00, 'is_featured' => false, 'sort_order' => 90],
        ['category_slug' => 'sogukkahve', 'name' => 'Ice Vanilya latte', 'description' => '', 'note' => '', 'price' => 200.00, 'is_featured' => false, 'sort_order' => 91],
        ['category_slug' => 'sogukkahve', 'name' => 'Ice Cappuccino', 'description' => '', 'note' => '', 'price' => 200.00, 'is_featured' => false, 'sort_order' => 92],
        ['category_slug' => 'soguk', 'name' => 'Taze Sıkılmış Portakal Suyu', 'description' => '', 'note' => '', 'price' => 190.00, 'is_featured' => false, 'sort_order' => 93],
        ['category_slug' => 'soguk', 'name' => 'Havuç Suyu', 'description' => '', 'note' => '', 'price' => 200.00, 'is_featured' => false, 'sort_order' => 94],
        ['category_slug' => 'soguk', 'name' => 'Cappy Meyve Suyu', 'description' => '', 'note' => '', 'price' => 90.00, 'is_featured' => false, 'sort_order' => 95],
        ['category_slug' => 'soguk', 'name' => 'Karışık Atom', 'description' => 'Elma, Havuç ve Portakal', 'note' => '', 'price' => 220.00, 'is_featured' => false, 'sort_order' => 96],
        ['category_slug' => 'soguk', 'name' => 'Elma Suyu', 'description' => '', 'note' => '', 'price' => 200.00, 'is_featured' => false, 'sort_order' => 97],
        ['category_slug' => 'soguk', 'name' => 'Sade Soda', 'description' => '', 'note' => '', 'price' => 60.00, 'is_featured' => false, 'sort_order' => 98],
        ['category_slug' => 'soguk', 'name' => 'Meyveli Soda', 'description' => '', 'note' => '', 'price' => 70.00, 'is_featured' => false, 'sort_order' => 99],
        ['category_slug' => 'soguk', 'name' => 'İtalyan Soda', 'description' => 'Çilek, Yeşil Elma', 'note' => '', 'price' => 200.00, 'is_featured' => false, 'sort_order' => 100],
        ['category_slug' => 'soguk', 'name' => 'Limonata', 'description' => 'Çilekli, Limonlu', 'note' => '', 'price' => 100.00, 'is_featured' => false, 'sort_order' => 101],
        ['category_slug' => 'soguk', 'name' => 'Milkshake', 'description' => 'Çikolatalı, Muzlu, Oreolu, Çilekli, Vanilyalı, Karamelli, Orman Meyveli', 'note' => '', 'price' => 220.00, 'is_featured' => false, 'sort_order' => 102],
        ['category_slug' => 'soguk', 'name' => 'Sprite', 'description' => '', 'note' => '', 'price' => 90.00, 'is_featured' => false, 'sort_order' => 103],
        ['category_slug' => 'soguk', 'name' => 'Gazoz', 'description' => '', 'note' => '', 'price' => 90.00, 'is_featured' => false, 'sort_order' => 104],
        ['category_slug' => 'soguk', 'name' => 'Fanta', 'description' => '', 'note' => '', 'price' => 90.00, 'is_featured' => false, 'sort_order' => 105],
        ['category_slug' => 'soguk', 'name' => 'Kola', 'description' => '', 'note' => '', 'price' => 90.00, 'is_featured' => false, 'sort_order' => 106],
        ['category_slug' => 'soguk', 'name' => 'Enerji İçecekleri Çeşitleri', 'description' => '', 'note' => '', 'price' => 170.00, 'is_featured' => false, 'sort_order' => 107],
        ['category_slug' => 'soguk', 'name' => 'Ayran Büyük', 'description' => '', 'note' => '', 'price' => 60.00, 'is_featured' => false, 'sort_order' => 108],
        ['category_slug' => 'tatlilar', 'name' => 'Meyve Tabağı', 'description' => 'Meyveler mevsimine göre değişiklik gösterir.', 'note' => '', 'price' => 450.00, 'is_featured' => true, 'sort_order' => 109],
        ['category_slug' => 'tatlilar', 'name' => 'Pasta Çeşitleri', 'description' => '', 'note' => '', 'price' => 270.00, 'is_featured' => false, 'sort_order' => 110],
        ['category_slug' => 'tatlilar', 'name' => 'Magnolia', 'description' => 'Çilekli Oreolu', 'note' => '', 'price' => 200.00, 'is_featured' => false, 'sort_order' => 111],
        ['category_slug' => 'tatlilar', 'name' => 'Supangle', 'description' => '', 'note' => '', 'price' => 200.00, 'is_featured' => false, 'sort_order' => 112],
        ['category_slug' => 'tatlilar', 'name' => 'Churros', 'description' => '', 'note' => '', 'price' => 350.00, 'is_featured' => false, 'sort_order' => 113],
        ['category_slug' => 'tatlilar', 'name' => 'Krep Waffle', 'description' => '', 'note' => '', 'price' => 350.00, 'is_featured' => false, 'sort_order' => 114],
        ['category_slug' => 'tatlilar', 'name' => 'Antep Fıstıklı Dondurmalı Krep Waffle', 'description' => '', 'note' => '', 'price' => 400.00, 'is_featured' => false, 'sort_order' => 115],
        ['category_slug' => 'tatlilar', 'name' => 'Meyveli Waffle', 'description' => 'Çilekli Muz, Çikolata', 'note' => '', 'price' => 450.00, 'is_featured' => false, 'sort_order' => 116],
        ['category_slug' => 'tatlilar', 'name' => 'Spagetti Waffle', 'description' => '', 'note' => '', 'price' => 300.00, 'is_featured' => false, 'sort_order' => 117],
        ['category_slug' => 'tatlilar', 'name' => 'Sufle', 'description' => '', 'note' => '', 'price' => 250.00, 'is_featured' => false, 'sort_order' => 118],
        ['category_slug' => 'tatlilar', 'name' => 'Dondurmalı Sufle', 'description' => '', 'note' => '', 'price' => 250.00, 'is_featured' => false, 'sort_order' => 119],
        ['category_slug' => 'tatlilar', 'name' => 'Muzlu Spoonful', 'description' => '', 'note' => '', 'price' => 220.00, 'is_featured' => false, 'sort_order' => 120],
        ['category_slug' => 'tatlilar', 'name' => 'Spoonful', 'description' => '', 'note' => '', 'price' => 220.00, 'is_featured' => false, 'sort_order' => 121],
        ['category_slug' => 'tatlilar', 'name' => 'Fırında Sütlaç', 'description' => '', 'note' => '', 'price' => 180.00, 'is_featured' => false, 'sort_order' => 122],
        ['category_slug' => 'kuruyemis', 'name' => 'Fındık', 'description' => '', 'note' => '', 'price' => 220.00, 'is_featured' => false, 'sort_order' => 123],
        ['category_slug' => 'kuruyemis', 'name' => 'Kaju', 'description' => '', 'note' => '', 'price' => 190.00, 'is_featured' => false, 'sort_order' => 124],
        ['category_slug' => 'kuruyemis', 'name' => 'Tuzlu Fıstık', 'description' => '', 'note' => '', 'price' => 120.00, 'is_featured' => false, 'sort_order' => 125],
        ['category_slug' => 'kuruyemis', 'name' => 'Antep Fıstığı', 'description' => '', 'note' => '', 'price' => 270.00, 'is_featured' => false, 'sort_order' => 126],
        ['category_slug' => 'kuruyemis', 'name' => 'Çekirdek', 'description' => '', 'note' => '', 'price' => 90.00, 'is_featured' => false, 'sort_order' => 127],
        ['category_slug' => 'kuruyemis', 'name' => 'Üzüm', 'description' => '', 'note' => '', 'price' => 100.00, 'is_featured' => false, 'sort_order' => 128],
        ['category_slug' => 'kuruyemis', 'name' => 'Badem', 'description' => '', 'note' => '', 'price' => 190.00, 'is_featured' => false, 'sort_order' => 129],
    ],
];
